
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 11 14:41:49 CST 2018
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETES = 61;
  public static final int OMENOSN = 40;
  public static final int ICORCH2 = 32;
  public static final int READLINE = 59;
  public static final int FCORCH = 57;
  public static final int CORCHETESC = 8;
  public static final int ENTERO = 3;
  public static final int DOUBLE = 29;
  public static final int PARENTESIS = 54;
  public static final int INTERFACE = 12;
  public static final int INT = 27;
  public static final int FIN = 34;
  public static final int FOR = 16;
  public static final int NOIGUAL = 49;
  public static final int AND = 50;
  public static final int MENORIGUAL = 44;
  public static final int READINTEGER = 58;
  public static final int IGUAL = 48;
  public static final int OMENOS = 38;
  public static final int OR = 52;
  public static final int CDOUBLE = 4;
  public static final int BOOL = 28;
  public static final int CLASS = 9;
  public static final int ANDAND = 51;
  public static final int FPAR = 36;
  public static final int OMAS = 37;
  public static final int IF = 13;
  public static final int THIS = 21;
  public static final int GETBYTE = 25;
  public static final int OMULT = 39;
  public static final int MAYORIGUAL = 46;
  public static final int SETBYTE = 26;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int ASIG = 47;
  public static final int RETURN = 17;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int CADENA = 6;
  public static final int NEGACION = 53;
  public static final int MENOR = 43;
  public static final int NULL = 20;
  public static final int OPORC = 41;
  public static final int BREAK = 18;
  public static final int IDENT = 2;
  public static final int VOID = 7;
  public static final int IPAR = 35;
  public static final int ICORCH = 56;
  public static final int MAYOR = 45;
  public static final int ELSE = 14;
  public static final int PUNTO = 55;
  public static final int WHILE = 15;
  public static final int EXTENDS = 10;
  public static final int ODIV = 42;
  public static final int HEXADECIMAL = 60;
  public static final int STRING = 30;
  public static final int MALLOC = 24;
  public static final int IMPLEMENTS = 11;
  public static final int NEWA = 23;
  public static final int PRINT = 19;
  public static final int FCORCH2 = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "ENTERO",
  "CDOUBLE",
  "BOOLEAN",
  "CADENA",
  "VOID",
  "CORCHETESC",
  "CLASS",
  "EXTENDS",
  "IMPLEMENTS",
  "INTERFACE",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "PRINT",
  "NULL",
  "THIS",
  "NEW",
  "NEWA",
  "MALLOC",
  "GETBYTE",
  "SETBYTE",
  "INT",
  "BOOL",
  "DOUBLE",
  "STRING",
  "COMA",
  "ICORCH2",
  "FCORCH2",
  "FIN",
  "IPAR",
  "FPAR",
  "OMAS",
  "OMENOS",
  "OMULT",
  "OMENOSN",
  "OPORC",
  "ODIV",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "ASIG",
  "IGUAL",
  "NOIGUAL",
  "AND",
  "ANDAND",
  "OR",
  "NEGACION",
  "PARENTESIS",
  "PUNTO",
  "ICORCH",
  "FCORCH",
  "READINTEGER",
  "READLINE"
  };
}

