/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package analizador;

/**
 *
 * @author Carlos
 */
public enum Token {
    OMAS, OMENOS, OMULT, ODIV, OPORC, MENOR, MENORIGUAL, MAYOR, MAYORIGUAL,ASIG,IGUAL, NOIGUAL, AND, OR, NEGACION,FIN,COMA,PUNTO, ICORCH,FCORCH,IPAR,FPAR,ICORCH2,FCORCH2,CORCHETESC,PARENTESIS,CORCHETES,ID,ENTERO,HEXADECIMAL,DOUBLECONSTANT,BOOLEAN,VOID,INT,DOUBLE,BOOL, STRING,CLASS,INTERFACE,NULL, THIS,EXTENDS,IMPLEMENTS,FOR,WHILE,IF,ELSE,RETURN,BREAK,NEW, NEWA, COMENTARIO, CADENA, ERROR
}
